using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace HelloCecelia
{
    public partial class Index : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void cmdChangeColor_Click(object sender, EventArgs e)
        {
            // This code runs when the user clicks the button cmdChangeColor in the web page. This was generated by double clicking the button in design view.
            // "Event Driven Programming". The event was the button click 
            lblHello.BackColor=System.Drawing.Color.BlueViolet;
        }

        protected void txtInsertTime_TextChanged(object sender, EventArgs e)
        {
            // Activates when the user changes the contents of the text box
        }

        protected void cmdTimeButton_Click(object sender, EventArgs e)
        {
            // The click event handler for the cmdTimeButton click
            txtInsertTime.Text = System.DateTime.Now.ToString();
        }

        protected void changeColor()
        {
            // We have a label object called lblHello. Change the foreground color to white. Invoke this method on the server side
            lblHello.ForeColor = System.Drawing.Color.White;
        }

        protected void cmdChangeForeColor_Click(object sender, EventArgs e)
        {
            changeColor();
        }
    }
}